project:
  name: "eddi-lab"
  description: "Interactive installation ecosystem with spatial intelligence"
  default_models:
    fast: "llama3"
    production: "claude-3-5-sonnet"

model_profiles:
  development:
    - model: "llama3"
      provider: "ollama"
      cost_per_token: 0.0
      temperature: 0.1
  
  production:
    - model: "claude-3-5-sonnet"
      provider: "anthropic"
      cost_per_token: 0.000003
      temperature: 0.1

integrations:
  github:
    enabled: true
    default_branch: "main"
    repositories:
      - "eddi-lab"
      - "StreamPoseML" 
      - "eddi"
      - "eddi-pad"
      - "skeleton-mhi"
      - "llm-orc"